export const SET_WINDOW_LOADING = 'SET_WINDOW_LOADING';
export const SET_CONTAINER_LOADING = 'SET_CONTAINER_LOADING';
export const SET_ITEM_LOADING = 'SET_ITEM_LOADING';
export const SET_AUTH_WARNING = 'SET_AUTH_WARNING';
export const GET_SMU_SUCCESS = 'GET_SMU_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";




