export const SET_WINDOW_LOADING = 'SET_WINDOW_LOADING';
export const SET_CONTAINER_LOADING = 'SET_CONTAINER_LOADING';
export const SET_ITEM_LOADING = 'SET_ITEM_LOADING';
export const SET_FORM_MESSAGE = 'SET_FORM_MESSAGE';


export const SET_AUTH_WARNING = 'SET_AUTH_WARNING';
export const GET_SMU_SUCCESS = 'GET_SMU_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";

export const CREATE_COUNTRY = 'CREATE_COUNTRY';
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_COUNTRY = 'FETCH_COUNTRY';
export const EDIT_COUNTRY = 'EDIT_COUNTRY';
export const DELETE_COUNTRY = 'DELETE_COUNTRY';

export const CREATE_SHAPE = 'CREATE_SHAPE';
export const FETCH_SHAPES = 'FETCH_SHAPES';
export const FETCH_SHAPE = 'FETCH_SHAPE';
export const EDIT_SHAPE = 'EDIT_SHAPE';
export const DELETE_SHAPE = 'DELETE_SHAPE';

export const CREATE_COLOR = 'CREATE_COLOR';
export const FETCH_COLORS = 'FETCH_COLORS';
export const FETCH_COLOR = 'FETCH_COLOR';
export const EDIT_COLOR = 'EDIT_COLOR';
export const DELETE_COLOR = 'DELETE_COLOR';

export const CREATE_BRAND = 'CREATE_BRAND';
export const FETCH_BRANDS = 'FETCH_BRANDS';
export const FETCH_BRAND = 'FETCH_BRAND';
export const FETCH_BRANDS_BY_PAGE = 'FETCH_BRANDS_BY_PAGE';
export const FETCH_SORTED_BRANDS = 'FETCH_SORTED_BRANDS';
export const FETCH_SERACHED_BRANDS = 'FETCH_SERACHED_BRANDS';
export const EDIT_BRAND = 'EDIT_BRAND';
export const DELETE_BRAND = 'DELETE_BRAND';

export const CREATE_SOURCE = 'CREATE_SOURCE';
export const FETCH_SOURCES = 'FETCH_SOURCES';
export const FETCH_SOURCE = 'FETCH_SOURCE';
export const FETCH_SOURCES_BY_PAGE = 'FETCH_SOURCES_BY_PAGE';
export const FETCH_SORTED_SOURCES = 'FETCH_SORTED_SOURCES';
export const FETCH_SEARCHED_SOURCES = 'FETCH_SEARCHED_SOURCES';
export const EDIT_SOURCE = 'EDIT_SOURCE';
export const DELETE_SOURCE = 'DELETE_SOURCE';


export const CREATE_NAME = 'CREATE_NAME';
export const FETCH_NAMES = 'FETCH_NAMES';
export const FETCH_NAME = 'FETCH_NAME';
export const EDIT_NAME = 'EDIT_NAME';
export const DELETE_NAME = 'DELETE_NAME';


export const CREATE_CIGAR = 'CREATE_CIGAR';
export const FETCH_CIGARS = 'FETCH_CIGARS';
export const FETCH_CIGAR = 'FETCH_CIGAR';
export const EDIT_CIGAR = 'EDIT_CIGAR';
export const DELETE_CIGAR = 'DELETE_CIGAR';


